# Generated by Django 4.2.4 on 2023-11-14 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UrlsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='sub',
        ),
        migrations.AddField(
            model_name='suburls',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root', to='UrlsApp.suburls', verbose_name='дочерние url'),
        ),
    ]
