# Generated by Django 4.2.4 on 2023-11-14 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UrlsApp', '0002_remove_urls_sub_suburls_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suburls',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root', to='UrlsApp.urls', verbose_name='корневой url'),
        ),
    ]
